name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Checkout theme repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: theme-next/hexo-theme-next
      #     ref: master
      #     path: themes/nexo
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: add_createtime
        run: python3 lib/add_createtime.py
      - name: change_ctime
        run: python3 lib/fix_mtime.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public